// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesOrderApp.Data;

#nullable disable

namespace SalesOrderApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250424051916_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesOrderApp.Models.COM_CUSTOMER", b =>
                {
                    b.Property<int>("COM_CUSTOMER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("COM_CUSTOMER_ID"));

                    b.Property<string>("CUSTOMER_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("COM_CUSTOMER_ID");

                    b.ToTable("COM_CUSTOMER", (string)null);
                });

            modelBuilder.Entity("SalesOrderApp.Models.SO_ITEM", b =>
                {
                    b.Property<long>("SO_ITEM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SO_ITEM_ID"));

                    b.Property<string>("ITEM_NAME")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<double>("PRICE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int>("QUANTITY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(-99);

                    b.Property<long>("SO_ORDER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(-99L);

                    b.HasKey("SO_ITEM_ID");

                    b.HasIndex("SO_ORDER_ID");

                    b.ToTable("SO_ITEM", (string)null);
                });

            modelBuilder.Entity("SalesOrderApp.Models.SO_ORDER", b =>
                {
                    b.Property<long>("SO_ORDER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SO_ORDER_ID"));

                    b.Property<string>("ADDRESS")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<int>("COM_CUSTOMER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(-99);

                    b.Property<DateTime>("ORDER_DATE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("ORDER_NO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.HasKey("SO_ORDER_ID");

                    b.HasIndex("COM_CUSTOMER_ID");

                    b.ToTable("SO_ORDER", (string)null);
                });

            modelBuilder.Entity("SalesOrderApp.Models.SO_ITEM", b =>
                {
                    b.HasOne("SalesOrderApp.Models.SO_ORDER", null)
                        .WithMany("Items")
                        .HasForeignKey("SO_ORDER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SalesOrderApp.Models.SO_ORDER", b =>
                {
                    b.HasOne("SalesOrderApp.Models.COM_CUSTOMER", "Customer")
                        .WithMany()
                        .HasForeignKey("COM_CUSTOMER_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SalesOrderApp.Models.SO_ORDER", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
